# Ross Built - Email Intel: CONFIG EXAMPLE / ENV REFERENCE
# =============================================================================
# You do NOT edit this file and you do NOT normally create a config.py of your
# own. config.py (committed) reads EVERYTHING from the ENVIRONMENT. This file is
# a documented reference of every variable it reads, with placeholder values.
#
# HOW TO SET THESE:
#   * SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY / ANTHROPIC_API_KEY already live
#     in the repo-root .env (…/weekly-meetings/.env) -- config.py loads that.
#   * Add the AZURE_* and behavior vars to that same repo-root .env, OR export
#     them in your shell / Task Scheduler action, OR drop an optional
#     email-intel/.env (loaded with override) next to this file.
#   * NEVER put a real secret in a committed file. NEVER pass a password as an
#     arg -- the device/app OAuth flows handle auth, no passwords anywhere.
#
# A .env-style copy of the same thing (paste into repo-root .env and fill in):
#
#   # --- already present in repo-root .env ---
#   SUPABASE_URL=https://YOUR-PROJECT.supabase.co
#   SUPABASE_SERVICE_ROLE_KEY=YOUR-SERVICE-ROLE-KEY      # service_role, NOT anon
#   ANTHROPIC_API_KEY=sk-ant-...
#
#   # --- Azure app registration (see SETUP.md) ---
#   AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000
#   AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
#   AZURE_CLIENT_SECRET=                                 # app mode (Phase 4) ONLY
#
#   # --- auth mode + mailboxes ---
#   AUTH_MODE=device                                     # "device" (default) | "app"
#   MAILBOX_LABEL=jake                                   # device mode: watermark key
#   PM_MAILBOXES=pm1@rossbuilt.com,pm2@rossbuilt.com     # app mode: sweep list
#                                                        # (blank -> derived from jobs.pm_email)
#
#   # --- behavior knobs (safe defaults) ---
#   DAYS_BACK_ON_FIRST_RUN=7                             # first-run history window
#   MAX_EMAILS_PER_RUN=200                               # cost guard, PER mailbox
#
#   # --- models (optional; app_config -> env -> default) ---
#   INTEL_EXTRACT_MODEL=claude-haiku-4-5-20251001        # cheap, extraction/triage
#   INTEL_ANALYZE_MODEL=claude-sonnet-4-6                # smarter, PM review
# =============================================================================

# --- Supabase (Supabase Dashboard -> Project Settings -> API) ---------------
SUPABASE_URL = "https://YOUR-PROJECT.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "YOUR-SERVICE-ROLE-KEY"   # the service_role key, NOT anon

# --- Anthropic (console.anthropic.com -> API keys) --------------------------
ANTHROPIC_API_KEY = "sk-ant-..."

# --- Microsoft / Azure app registration (see SETUP.md) ----------------------
AZURE_CLIENT_ID = "YOUR-APPLICATION-CLIENT-ID"
AZURE_TENANT_ID = "YOUR-DIRECTORY-TENANT-ID"
AZURE_CLIENT_SECRET = ""   # leave blank for device mode; required for AUTH_MODE=app

# --- Auth mode --------------------------------------------------------------
# "device": Phase 1 default. Device-code browser login; reads YOUR OWN sent mail.
# "app":    Phase 4. Client-credentials; reads a LIST of PM mailboxes unattended.
AUTH_MODE = "device"

# --- Mailboxes --------------------------------------------------------------
MAILBOX_LABEL = "jake"   # device mode: any stable label; keys this mailbox's watermark
PM_MAILBOXES = "pm1@rossbuilt.com, pm2@rossbuilt.com"  # app mode: comma/space separated
#                                                       # (blank -> derived from jobs.pm_email)

# --- Behavior (safe defaults) -----------------------------------------------
DAYS_BACK_ON_FIRST_RUN = 7     # how much history to pull the very first run
MAX_EMAILS_PER_RUN = 200       # cost guard so a backlog can't surprise-bill you (per mailbox)

# --- Models (optional overrides; resolution: app_config -> env -> default) --
INTEL_EXTRACT_MODEL = "claude-haiku-4-5-20251001"  # cheap, for triage/extraction
INTEL_ANALYZE_MODEL = "claude-sonnet-4-6"          # smarter, for the PM review
